language: cpp

compiler:
    - clang
    - gcc

sudo: required

before_install:
    - sudo apt-get purge cmake
    - sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y
    - sudo apt-get update -q
    - sudo apt-get install cmake=2.8.12.2-0~13~ubuntu12.04.1
    - cmake -DBUILD_TEST=1 .

script:
    - make && ./MainTest

#addons:
#  apt:
#    sources:
#    - andykimpe

#addons:
#  apt:
#    packages:
#    - cmake
