language: cpp

compiler:
    - clang
    - gcc

sudo: required

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
    - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - sudo apt-get purge cmake
    - sudo apt-get purge sqlite3
    - sudo apt-get install cmake=2.8.12.2-0~13~ubuntu12.04.1
    # Install sqlite 3.7.11+
    - sudo apt-get install tcl -y
    - wget http://www.sqlite.org/cgi/src/tarball/SQLite-a71e2a72.tar.gz -O sqlite3.7.11.tar.gz
    - tar -xf sqlite3.7.11.tar.gz
    - cd SQLite-a71e2a72 && ./configure --prefix=/usr/local && make && sudo make install && cd ..
    - sqlite3 --version

before_script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TEST=1 ..

script:
    - make && ./MainTest

#addons:
#  apt:
#    sources:
#    - andykimpe

#addons:
#  apt:
#    packages:
#    - cmake
