language: cpp

compiler:
    - clang
    - gcc

sudo: false

#before_script:
#    - sudo add-apt-repository ppa:andykimpe/cmake3 -y
#    - sudo apt-get update -q
#    - sudo apt-get install cmake

addons:
  apt:
    sources:
    - andykimpe

addons:
  apt:
    packages:
    - cmake3

before_install:
    - cmake -DBUILD_TEST=1