language: cpp

compiler:
    - clang
    - gcc

sudo: required

before_install:
    - sudo add-apt-repository ppa:andykimpe/cmake3 -y
    - sudo apt-get update -q
    - sudo apt-get install cmake3
    - cmake -DBUILD_TEST=1
#addons:
#  apt:
#    sources:
#    - andykimpe

#addons:
#  apt:
#    packages:
#    - cmake
