language: cpp

compiler:
    - clang
    - gcc

before_install:
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
    - tar xf cmake-3.2.2.tar.gz
    - cd cmake-3.2.2
    - ./configure
    - make
    - cmake -DBUILD_TEST=1