language: cpp

compiler:
    - clang
    - gcc

before_script:
    - sudo add-apt-repository -y ppa:andykimpe/cmake3
    - sudo apt-get update -q
    - sudo apt-get install cmake

before_install
    - cmake -DBUILD_TEST=1